### ISSUE TITLE
Pex fails on remote server

### ISSUE THREAD

**Issue by kuza55** [kuza55/pants_debug_mysql#1]
Build pex like so:
```
pants package src:main
```

When run on a different Ubuntu machine, the built pex crashes:

```
$ ./main.pex
Traceback (most recent call last):
  File "/home/ubuntu/.pex/installed_wheels/7e5ec5d2771843651682b64376e5e9ce51e1e81eff997da3a3953c4a2b0d200e/mysqlclient-2.1.1-cp310-cp310-linux_x86_64.whl/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmysqlclient.so.21: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/__main__.py", line 103, in <module>
    bootstrap_pex(__entry_point__, execute=__execute__, venv_dir=__venv_dir__)
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex_bootstrapper.py", line 599, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex.py", line 551, in execute
    sys.exit(self._wrap_coverage(self._wrap_profiling, self._execute))
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex.py", line 458, in _wrap_coverage
    return runner(*args)
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex.py", line 489, in _wrap_profiling
    return runner(*args)
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex.py", line 594, in _execute
    return self.execute_entry(
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex.py", line 775, in execute_entry
    return self.execute_module(entry_point.module)
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/.bootstrap/pex/pex.py", line 783, in execute_module
    runpy.run_module(module_name, run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pex/unzipped_pexes/a9ce37a6cce055c0f8a5e242c32402d3db3381f5/main.py", line 11, in <module>
    engine = db.create_engine(db_string, pool_size=20, max_overflow=20)
  File "<string>", line 2, in create_engine
  File "/home/ubuntu/.pex/installed_wheels/d67c6d55492e9ec8e1957e6932d82e21eab72c347661953a210994de7214974c/SQLAlchemy-2.0.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/ubuntu/.pex/installed_wheels/d67c6d55492e9ec8e1957e6932d82e21eab72c347661953a210994de7214974c/SQLAlchemy-2.0.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/sqlalchemy/engine/create.py", line 601, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/home/ubuntu/.pex/installed_wheels/d67c6d55492e9ec8e1957e6932d82e21eab72c347661953a210994de7214974c/SQLAlchemy-2.0.16-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/sqlalchemy/dialects/mysql/mysqldb.py", line 152, in import_dbapi
    return __import__("MySQLdb")
  File "/home/ubuntu/.pex/installed_wheels/7e5ec5d2771843651682b64376e5e9ce51e1e81eff997da3a3953c4a2b0d200e/mysqlclient-2.1.1-cp310-cp310-linux_x86_64.whl/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

**Comment by benjyw** [comment]
What platform (os/arch) did you build the pex on and which are you running it on?

**Comment by kuza55** [comment]
I built this on Ubuntu in WSL on x86_64 and am trying to run it on Ubuntu on x86_64 (whicheverversion AWS uses as the default).

**Comment by sureshjoshi** [comment]
Asking as a sanity check - is the mysqlclient installed on AWS Ubuntu by default?

`apt install libmysqlclient` or `apt install libmysqlclient-dev`

**Comment by kuza55** [comment]
It is not; I was hoping to bundle all of this inside a pex.

**Comment by sureshjoshi** [comment]
Gotcha, so all the native mysqlclient compilation deps are installed - and then you build the pex, which pulls down a wheel, which contains the mysql lib?

https://github.com/PyMySQL/mysqlclient#linux


If so, if you unzip the pex file - are the expected files there?

**Comment by jsirois** [comment]
This is a no go, the wheel is not manylinux compliant and more broadly requires MySQL client be pre-installed on the host regardless of OS. Pex does not, in fact, attempt to bundle host shared libraries. You'll have to arrange for the MySQL client library to be installed on whatever hosts you run the PEX file on.

**Comment by benjyw** [comment]
Sounds like this is not possible since that library is a wrapper around the pre-installed mysql client: https://pantsbuild.slack.com/archives/C046T6T9U/p1686460423003249?thread_ts=1686441191.813009&cid=C046T6T9U
